--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SOF3/await-std
build-by-default: true
branches:
- master
- pm4
projects:
  await-std:
    path: ""
    model: virion
    type: library
    libs:
      - src: SOF3/await-generator-await-generator
        version: "^3.0.0"
...
